### ISSUE TITLE
Tree layout configuration

### ISSUE THREAD

**Issue by otardiolo** [nevakee716/Tree#1]
Hi,
it should be possible to avoid overlapping items when using Tree Layout, by setting a higher spacing or a newline after a specific amount of characters. See below image for details on my issue
![tree layout](https://user-images.githubusercontent.com/36473325/41646675-bcf0f52a-7474-11e8-9eca-a7bdec833149.PNG)

thank you.
Omar

**Comment by nevakee716** [comment]
Corrected you can download the last version of the layout 
at https://github.com/ErwinConsultingFrance/evolve-layouts

**Comment by otardiolo** [comment]
I think there's something wrong with the new version of tree layout, in terms of displayed data.
I have 2 branches, and each branch shows also the association of the other branch.
I didn't have this behavior with the previous version, but maybe I could have done some mistakes in the configuration

**Comment by nevakee716** [comment]
can you put a screen of your configuration in evolve,

**Comment by otardiolo** [comment]
![errora](https://user-images.githubusercontent.com/36473325/41721032-204dceea-7565-11e8-8359-6249789b2092.PNG)
each branch shows "Servizio Informatico" with both "GDPR" and "Business" associations mixed togheter.
I would like one branch with "Servizio Informatico"->"GDPR"->"Categoria Dati Personali" and the other with "Servizio Informatico"->"Business"->"Struttura Organizzativa"

thank you,
omar

**Comment by otardiolo** [comment]
![error2](https://user-images.githubusercontent.com/36473325/41721504-56388602-7566-11e8-955e-96bf6f44a419.PNG)
first level are "Servizio Informatico" objects while on the second level there are both "Business" items (highlighted in yellow") and "GDPR" items, but according to Evolve designer definition, only "Business" items should be in that branch.
thank you,
Omar
